package com.robot.command;

public enum CommandKey {
	LEFT_CLICK,
	RIGHT_CLICK,
	PRESS_UP,
	PRESS_DOWN,
	PRESS_LEFT,
	PRESS_RIGHT,
	PRESS_ESC,
	CHECK_OPTION_BOX,
	CHECK_NEIGHBORS,
	RANDOM_MOVE_CAMERA,
	SAVE_PIXEL_COLOR,
	CHECK_PIXEL_COLOR
}
